namespace knights_challenge_logger.Models
{
    public class LogMessage
    {
        // Microservice where the logs originate
        public required string ServiceName { get; set; }
        // Ex.: Authorization, Battle logs, etc
        public required string LogType { get; set; }
        // Generated during the event by the microservice 
        public required DateTime EventTimestamp { get; set; }
        // Generated by the LoggerService microservice
        public DateTime ReceivedTimestamp { get; set; } = DateTime.UtcNow;
        // Metadata and unique information
        public Dictionary<string, object>? Metadata { get; set; }
    }
}
